services:
  # 🗄️ Database 
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - cctv-network

  # 🎥 Streaming (go2rtc)
  go2rtc:
    image: alexxit/go2rtc
    restart: always
    network_mode: host 
    volumes:
      - ./cctv-backend/go2rtc.yaml:/config/go2rtc.yaml

  # ⚙️ Backend API
  backend:
    build:
      context: ./cctv-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
      GO2RTC_URL: "http://host.docker.internal:1984"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cctv-network

  # 💻 Frontend (React + Nginx)
  frontend:
    build:
      context: ./cctv-frontend
      dockerfile: Dockerfile
    restart: always
    #เพิ่ม: เปิด Port 80 ของเครื่อง .89 ให้ NPM จาก .80 ยิงเข้ามาได้
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cctv-network

networks:
  cctv-network:
    driver: bridge